language: "perl"
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: "perl Makefile.PL; make test"

notifications:
  recipients:
    - dana@acm.org
  email:
    on_success: change
    on_failure: always
